#!/bin/bash
# Build a tiny protein kraken2 database for testing translated search.
#
# Needs kraken2-build (bioconda kraken2) and python3 on the PATH. The
# taxonomy, proteins and reads are synthetic and generated by
# make_protein_testdata.py, so no NCBI download is required.
#
# Usage: ./make_protein_db.sh [dbdir]   (default: tinyprot)

set -euo pipefail

cd "$(dirname "$0")"
DB=${1:-tinyprot}

if [ -f "$DB/hash.k2d" ]; then
    echo "+++ Protein database $DB already built +++"
    exit 0
fi

echo "+++ Generating synthetic proteins and reads +++"
rm -rf "$DB"
python3 make_protein_testdata.py "$DB"

echo "+++ Building protein database +++"
kraken2-build --protein --db "$DB" --add-to-library "$DB/library.faa" --no-masking > "$DB/build.log" 2>&1
kraken2-build --protein --db "$DB" --build --threads 2 >> "$DB/build.log" 2>&1
kraken2-build --db "$DB" --clean >> "$DB/build.log" 2>&1

ls -la "$DB"/*.k2d
echo "+++ Done: $DB +++"
