# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import Kraken2_pb2 as Kraken2__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in Kraken2_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Kraken2ServiceStub:
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ServerReady = channel.unary_unary(
                '/kraken2proto.Kraken2Service/ServerReady',
                request_serializer=Kraken2__pb2.Kraken2ReadyRequest.SerializeToString,
                response_deserializer=Kraken2__pb2.Kraken2ReadyResult.FromString,
                _registered_method=True)
        self.GetSummary = channel.unary_unary(
                '/kraken2proto.Kraken2Service/GetSummary',
                request_serializer=Kraken2__pb2.Kraken2SummaryRequest.SerializeToString,
                response_deserializer=Kraken2__pb2.Kraken2SummaryResults.FromString,
                _registered_method=True)
        self.RemoteShutdown = channel.unary_unary(
                '/kraken2proto.Kraken2Service/RemoteShutdown',
                request_serializer=Kraken2__pb2.Kraken2ShutdownRequest.SerializeToString,
                response_deserializer=Kraken2__pb2.Kraken2ShutdownResult.FromString,
                _registered_method=True)
        self.ClassifyStream = channel.stream_stream(
                '/kraken2proto.Kraken2Service/ClassifyStream',
                request_serializer=Kraken2__pb2.Kraken2SequenceRequestMulti.SerializeToString,
                response_deserializer=Kraken2__pb2.Kraken2SequenceStreamResult.FromString,
                _registered_method=True)


class Kraken2ServiceServicer:
    """Interface exported by the server.
    """

    def ServerReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoteShutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Kraken2ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ServerReady': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerReady,
                    request_deserializer=Kraken2__pb2.Kraken2ReadyRequest.FromString,
                    response_serializer=Kraken2__pb2.Kraken2ReadyResult.SerializeToString,
            ),
            'GetSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSummary,
                    request_deserializer=Kraken2__pb2.Kraken2SummaryRequest.FromString,
                    response_serializer=Kraken2__pb2.Kraken2SummaryResults.SerializeToString,
            ),
            'RemoteShutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoteShutdown,
                    request_deserializer=Kraken2__pb2.Kraken2ShutdownRequest.FromString,
                    response_serializer=Kraken2__pb2.Kraken2ShutdownResult.SerializeToString,
            ),
            'ClassifyStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ClassifyStream,
                    request_deserializer=Kraken2__pb2.Kraken2SequenceRequestMulti.FromString,
                    response_serializer=Kraken2__pb2.Kraken2SequenceStreamResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kraken2proto.Kraken2Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kraken2proto.Kraken2Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kraken2Service:
    """Interface exported by the server.
    """

    @staticmethod
    def ServerReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kraken2proto.Kraken2Service/ServerReady',
            Kraken2__pb2.Kraken2ReadyRequest.SerializeToString,
            Kraken2__pb2.Kraken2ReadyResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kraken2proto.Kraken2Service/GetSummary',
            Kraken2__pb2.Kraken2SummaryRequest.SerializeToString,
            Kraken2__pb2.Kraken2SummaryResults.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoteShutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kraken2proto.Kraken2Service/RemoteShutdown',
            Kraken2__pb2.Kraken2ShutdownRequest.SerializeToString,
            Kraken2__pb2.Kraken2ShutdownResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/kraken2proto.Kraken2Service/ClassifyStream',
            Kraken2__pb2.Kraken2SequenceRequestMulti.SerializeToString,
            Kraken2__pb2.Kraken2SequenceStreamResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
